#include <stdlib.h>
#include <stdio.h>
#include <pthread.h>
#define BUILDSTDLIB
#include "./cfiles/commonFunctions.h"
#include "./cfiles/graph.c"
#include "./cfiles/node.c"
#include "./cfiles/nodelist.c"
#include "./cfiles/edge.c"
#include "./cfiles/edgelist.c"
//#include "./cfiles/doubletable.c"
//#include "./cfiles/inttable.c"